//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZetaProducerHtmlCompressor.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZetaProducerHtmlCompressor.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta content=&quot;text/html; charset=utf-8&quot; http-equiv=&quot;Content-Type&quot; /&gt;
        ///	&lt;title&gt;Untitled 1&lt;/title&gt;
        ///&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;Head&lt;/h1&gt;
        ///		&lt;p&gt;This is just &lt;em&gt;a&lt;/em&gt; &lt;a href=&quot;http://www.google.com&quot;&gt;test&lt;/a&gt;.&lt;/p&gt;
        ///		&lt;p&gt;&lt;i class=&quot;icon-chevron-down&quot;&gt;&lt;/i&gt; &lt;i class=&quot;icon-chevron-down&quot;&gt;&lt;/i&gt;&lt;/p&gt;
        ///		&lt;p&gt;Finish!&lt;/p&gt;
        ///	&lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string Html01 {
            get {
                return ResourceManager.GetString("Html01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;de&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;!-- Title --&gt;
        ///    &lt;title&gt;Herzlich willkommen!&lt;/title&gt;
        ///
        ///    &lt;!-- Meta Data --&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot; /&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot; /&gt;
        ///    &lt;meta name=&quot;generator&quot; content=&quot;Zeta Producer 15.0.1.0, ZP12B, 14.04.2015 16:04:54&quot; /&gt;
        ///    &lt;meta name=&quot;robots&quot; content=&quot;index, follow&quot; /&gt;
        ///
        ///
        ///    &lt;!-- Favicon &amp; CSS --&gt;
        ///    &lt;link rel=&quot;shortcut icon&quot; type=&quot;image/x-icon&quot; href=&quot;assets/stock-files/favicon.ico&quot; /&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html02 {
            get {
                return ResourceManager.GetString("Html02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;de&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;!-- Title --&gt;
        ///    &lt;title&gt;Herzlich willkommen!&lt;/title&gt;
        ///
        ///    &lt;!-- Meta Data --&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot; /&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot; /&gt;
        ///    &lt;meta name=&quot;generator&quot; content=&quot;Zeta Producer 15.0.1.0, ZP12B, 14.04.2015 17:05:00&quot; /&gt;
        ///    &lt;meta name=&quot;robots&quot; content=&quot;index, follow&quot; /&gt;
        ///
        ///
        ///    &lt;!-- Favicon &amp; CSS --&gt;
        ///    &lt;link rel=&quot;shortcut icon&quot; type=&quot;image/x-icon&quot; href=&quot;assets/stock-files/favicon.ico&quot; /&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html02a {
            get {
                return ResourceManager.GetString("Html02a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a x=&quot;aaa &apos;bbb&apos; ccc&quot;  b=&quot;1&quot;&gt;   &lt;b   onclick  =  &quot;  alert(&apos;&lt;a&gt;   &lt;b&gt;&apos;)  &quot;  /&gt; &lt;c/&gt;   
        ///   &lt;d /&gt;
        ///&lt;pre    a   =   &quot;  1  &quot;&gt;    &lt;x   /&gt;    &lt;y&gt;   &lt;/pre&gt;
        ///&lt;!-- comment --&gt;
        ///&lt;!--[if lt IE 7 ]&gt;        &lt;body class=&quot;ie6&quot;&gt;      &lt;![endif]--&gt;           &lt;!--[if lt IE 7 ]&gt;        &lt;body class=&quot;ie6&quot;&gt;      &lt;![endif]--&gt;
        ///&lt;pre&gt;          &lt;!-- comment --&gt;     &lt;/pre&gt;
        ///&lt;textarea&gt;          &lt;!-- comment --&gt;     &lt;/textarea&gt;
        ///&lt;script&gt;          &lt;!-- comment --&gt;     &lt;/script&gt;
        ///&lt;script type=&quot;text/x-jquery-tmpl&quot;&gt;     &lt;a&gt;     &lt;!-- comment  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testCompress {
            get {
                return ResourceManager.GetString("testCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a q  =  &quot;qqq&quot;  w   =  &apos;ww&quot;w&quot;w&apos; &gt;   
        ///	&lt;b&gt;   
        ///		&lt;c&gt;
        ///			&lt;![CDATA[
        ///			&lt;a&gt;   &lt;b&gt;   &lt;!-- comment --&gt;   &lt;c&gt;
        ///			]]&gt;
        ///		&lt;/c&gt;
        ///	&lt;/b&gt;
        ///&lt;a&gt;
        ///&lt;x /&gt;
        ///&lt;y&gt;    aaa          bbbb          &lt;/y&gt;
        ///.
        /// </summary>
        internal static string testCompress1 {
            get {
                return ResourceManager.GetString("testCompress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style&gt;
        ///	/* comment */
        ///	color:   red;
        ///&lt;/style&gt;
        ///
        ///&lt;pre&gt;
        ///	&lt;style&gt;
        ///		/* comment */
        ///		color:   red;
        ///	&lt;/style&gt;
        ///&lt;/pre&gt;.
        /// </summary>
        internal static string testCompressCss {
            get {
                return ResourceManager.GetString("testCompressCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style&gt;color:red;&lt;/style&gt;&lt;pre&gt;
        ///	&lt;style&gt;
        ///		/* comment */
        ///		color:   red;
        ///	&lt;/style&gt;
        ///&lt;/pre&gt;.
        /// </summary>
        internal static string testCompressCssResult {
            get {
                return ResourceManager.GetString("testCompressCssResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;
        ///	var i = 0; //comment
        ///	i = i + 1;
        ///	alert(i);
        ///&lt;/script&gt;
        ///
        ///&lt;script&gt;
        ///	&lt;![CDATA[
        ///		var i = 0; //comment
        ///		i = i + 1;
        ///		alert(i);
        ///	]]&gt;
        ///&lt;/script&gt;
        ///
        ///&lt;pre&gt;
        ///	&lt;script&gt;
        ///		var i = 0; //comment
        ///		i = i + 1;
        ///		alert(i);
        ///	&lt;/script&gt;
        ///&lt;/pre&gt;
        ///
        ///&lt;script type=&quot;text/x-jquery-tmpl&quot;&gt;     &lt;a&gt;     &lt;!-- comment --&gt;   &lt;b&gt;   &lt;/script&gt;
        ///&lt;script type=&quot;text/custom&quot;&gt;  var i=1@#$%^2   &lt;a&gt;     &lt;!-- comment --&gt;   &lt;b&gt;   &lt;/script&gt;.
        /// </summary>
        internal static string testCompressJavaScript {
            get {
                return ResourceManager.GetString("testCompressJavaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;var a=0;a+=1;alert(a);&lt;/script&gt;&lt;script&gt;&lt;![CDATA[var a=0;a+=1;alert(a);]]&gt;&lt;/script&gt;&lt;pre&gt;
        ///	&lt;script&gt;
        ///		var i = 0; //comment
        ///		i = i + 1;
        ///		alert(i);
        ///	&lt;/script&gt;
        ///&lt;/pre&gt;&lt;script type=&quot;text/x-jquery-tmpl&quot;&gt;&lt;a&gt;&lt;b&gt;&lt;/script&gt;&lt;script type=&quot;text/custom&quot;&gt;  var i=1@#$%^2   &lt;a&gt;     &lt;!-- comment --&gt;   &lt;b&gt;   &lt;/script&gt;.
        /// </summary>
        internal static string testCompressJavaScriptClosureResult {
            get {
                return ResourceManager.GetString("testCompressJavaScriptClosureResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;var i=0;i=i+1;alert(i);&lt;/script&gt;&lt;script&gt;&lt;![CDATA[var i=0;i=i+1;alert(i);]]&gt;&lt;/script&gt;&lt;pre&gt;
        ///	&lt;script&gt;
        ///		var i = 0; //comment
        ///		i = i + 1;
        ///		alert(i);
        ///	&lt;/script&gt;
        ///&lt;/pre&gt;&lt;script type=&quot;text/x-jquery-tmpl&quot;&gt;&lt;a&gt;&lt;b&gt;&lt;/script&gt;&lt;script type=&quot;text/custom&quot;&gt;  var i=1@#$%^2   &lt;a&gt;     &lt;!-- comment --&gt;   &lt;b&gt;   &lt;/script&gt;.
        /// </summary>
        internal static string testCompressJavaScriptYuiResult {
            get {
                return ResourceManager.GetString("testCompressJavaScriptYuiResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a x=&quot;aaa &apos;bbb&apos; ccc&quot; b=&quot;1&quot;&gt; &lt;b onclick=&quot;  alert(&apos;&lt;a&gt;   &lt;b&gt;&apos;)  &quot;/&gt; &lt;c/&gt; &lt;d/&gt; &lt;pre a=&quot; 1 &quot;&gt;    &lt;x   /&gt;    &lt;y&gt;   &lt;/pre&gt; &lt;!--[if lt IE 7 ]&gt;&lt;body class=&quot;ie6&quot;&gt;&lt;![endif]--&gt; &lt;!--[if lt IE 7 ]&gt;&lt;body class=&quot;ie6&quot;&gt;&lt;![endif]--&gt; &lt;pre&gt;          &lt;!-- comment --&gt;     &lt;/pre&gt; &lt;textarea&gt;          &lt;!-- comment --&gt;     &lt;/textarea&gt; &lt;script&gt;          &lt;!-- comment --&gt;     &lt;/script&gt; &lt;script type=&quot;text/x-jquery-tmpl&quot;&gt; &lt;a&gt; &lt;b&gt; &lt;/script&gt; &lt;style&gt;          &lt;!-- comment --&gt;     &lt;/style&gt;.
        /// </summary>
        internal static string testCompressResult {
            get {
                return ResourceManager.GetString("testCompressResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a q=&quot;qqq&quot; w=&apos;ww&quot;w&quot;w&apos;&gt;&lt;b&gt;&lt;c&gt;
        ///			&lt;![CDATA[
        ///			&lt;a&gt;   &lt;b&gt;   &lt;!-- comment --&gt;   &lt;c&gt;
        ///			]]&gt;
        ///		&lt;/c&gt;&lt;/b&gt;&lt;a&gt;&lt;x/&gt;&lt;y&gt;    aaa          bbbb          &lt;/y&gt;.
        /// </summary>
        internal static string testCompressResult1 {
            get {
                return ResourceManager.GetString("testCompressResult1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html   &lt;!-- comment --&gt;   html.
        /// </summary>
        internal static string testEnabled {
            get {
                return ResourceManager.GetString("testEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a&gt;   &lt;b&gt;   &lt;!-- comment --&gt;.
        /// </summary>
        internal static string testEnabled1 {
            get {
                return ResourceManager.GetString("testEnabled1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html   &lt;!-- comment --&gt;   html.
        /// </summary>
        internal static string testEnabledResult {
            get {
                return ResourceManager.GetString("testEnabledResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a&gt;   &lt;b&gt;   &lt;!-- comment --&gt;.
        /// </summary>
        internal static string testEnabledResult1 {
            get {
                return ResourceManager.GetString("testEnabledResult1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a&gt;    
        ///
        ///
        ///	&lt;b&gt;      
        ///
        ///            
        ///		&lt;c/&gt;             
        ///
        ///
        ///	&lt;/b&gt;         
        ///&lt;/a&gt;           .
        /// </summary>
        internal static string testPreserveLineBreaks {
            get {
                return ResourceManager.GetString("testPreserveLineBreaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a&gt;
        ///&lt;b&gt;
        ///&lt;c/&gt;
        ///&lt;/b&gt;
        ///&lt;/a&gt;.
        /// </summary>
        internal static string testPreserveLineBreaksResult {
            get {
                return ResourceManager.GetString("testPreserveLineBreaksResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a&gt;       &lt;b&gt;
        ///&lt;!-- comment --&gt;
        ///&lt;?php   &lt;!-- comment --&gt;    ?&gt;
        ///&lt;%   &lt;!-- comment --&gt;   %&gt;
        ///&lt;jsp:   a   b   &gt;
        ///&lt;!-- #include --&gt;
        ///&lt;!--#include --&gt;.
        /// </summary>
        internal static string testPreservePatterns {
            get {
                return ResourceManager.GetString("testPreservePatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a&gt;&lt;b&gt;&lt;?php   &lt;!-- comment --&gt;    ?&gt;&lt;%   &lt;!-- comment --&gt;   %&gt;&lt;jsp:   a   b   &gt;&lt;!-- #include --&gt;&lt;!--#include --&gt;.
        /// </summary>
        internal static string testPreservePatternsResult {
            get {
                return ResourceManager.GetString("testPreservePatternsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- comment --&gt;&lt;!-- --&gt;&lt;!----&gt;&lt;!--
        ///--&gt;
        ///
        ///&lt;pre&gt; aaa &lt;!-- comment --&gt; bbb &lt;/pre&gt;
        ///
        ///&lt;!--[if lt IE 7 ]&gt;        &lt;body class=&quot;ie6&quot;&gt;      &lt;![endif]--&gt;
        ///&lt;!--[if IE 7 ]&gt;    &lt;body class=&quot;ie7&quot;&gt; &lt;pre&gt;  aaaaaa       sssssssss    &lt;/pre&gt;      &lt;![endif]--&gt;
        ///&lt;!--[if IE 8 ]&gt;    &lt;body class=&quot;ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 9 ]&gt;    &lt;body class=&quot;ie9&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if (gt IE 9)|!(IE)]&gt;&lt;!--&gt;     &lt;body&gt;       
        ///
        ///&lt;script&gt;
        ///	var i=0; //qweqwe
        ///	alert(&quot;qwe&quot;);
        ///&lt;/script&gt;
        ///
        ///&lt;!--&lt;![endif]--&gt;.
        /// </summary>
        internal static string testRemoveComments {
            get {
                return ResourceManager.GetString("testRemoveComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a&gt;   &lt;b&gt;   &lt;!-- comment --&gt;   &lt;c&gt;
        ///&lt;![CDATA[
        ///&lt;a&gt;   &lt;b&gt;   &lt;!-- comment --&gt;   &lt;c&gt;
        ///]]&gt;
        ///
        ///.
        /// </summary>
        internal static string testRemoveComments1 {
            get {
                return ResourceManager.GetString("testRemoveComments1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt; aaa &lt;!-- comment --&gt; bbb &lt;/pre&gt;&lt;!--[if lt IE 7 ]&gt;&lt;body class=&quot;ie6&quot;&gt;&lt;![endif]--&gt;&lt;!--[if IE 7 ]&gt;&lt;body class=&quot;ie7&quot;&gt;&lt;pre&gt;  aaaaaa       sssssssss    &lt;/pre&gt;&lt;![endif]--&gt;&lt;!--[if IE 8 ]&gt;&lt;body class=&quot;ie8&quot;&gt;&lt;![endif]--&gt;&lt;!--[if IE 9 ]&gt;&lt;body class=&quot;ie9&quot;&gt;&lt;![endif]--&gt;&lt;!--[if (gt IE 9)|!(IE)]&gt;&lt;!--&gt;&lt;body&gt;&lt;script&gt;
        ///	var i=0; //qweqwe
        ///	alert(&quot;qwe&quot;);
        ///&lt;/script&gt;&lt;!--&lt;![endif]--&gt;.
        /// </summary>
        internal static string testRemoveCommentsResult {
            get {
                return ResourceManager.GetString("testRemoveCommentsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a&gt;&lt;b&gt;&lt;c&gt;
        ///&lt;![CDATA[
        ///&lt;a&gt;   &lt;b&gt;   &lt;!-- comment --&gt;   &lt;c&gt;
        ///]]&gt;.
        /// </summary>
        internal static string testRemoveCommentsResult1 {
            get {
                return ResourceManager.GetString("testRemoveCommentsResult1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;form  method  = post&gt; &lt;form  method  = get&gt; &lt;form method=&quot;get&quot;&gt; &lt;form method=&apos;get&apos; name=&quot;name&quot;&gt;.
        /// </summary>
        internal static string testRemoveFormAttributes {
            get {
                return ResourceManager.GetString("testRemoveFormAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;form method=post&gt; &lt;form&gt; &lt;form&gt; &lt;form name=&quot;name&quot;&gt;.
        /// </summary>
        internal static string testRemoveFormAttributesResult {
            get {
                return ResourceManager.GetString("testRemoveFormAttributesResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;link href=&quot;http://leave&quot; rel=&apos;alternate external&apos;&gt;&lt;link href=&quot;http://leave&quot; rel=external&gt;&lt;link href=&quot;http://leave&quot; rel=&quot;external&quot;&gt;&lt;link href=&quot;http://example.com/style.css&quot;/&gt;&lt;script src  =  &apos;https://www.example.com/script.js&apos;&gt;&lt;/script&gt;&lt;a href= &quot;//google.com&quot;&gt;&lt;/a&gt;&lt;img src   = &quot;/pic.jpg&quot;&gt;&lt;img alt=&quot;http://leave&quot; src  =  &quot;https://img&quot;/&gt;.
        /// </summary>
        internal static string testRemoveHttpProtocol {
            get {
                return ResourceManager.GetString("testRemoveHttpProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;link href=&quot;http://leave&quot; rel=&apos;alternate external&apos;&gt;&lt;link href=&quot;http://leave&quot; rel=external&gt;&lt;link href=&quot;http://leave&quot; rel=&quot;external&quot;&gt;&lt;link href=&quot;//example.com/style.css&quot;/&gt;&lt;script src=&apos;https://www.example.com/script.js&apos;&gt;&lt;/script&gt;&lt;a href=&quot;//google.com&quot;&gt;&lt;/a&gt;&lt;img src=&quot;/pic.jpg&quot;&gt;&lt;img alt=&quot;http://leave&quot; src=&quot;https://img&quot;/&gt;.
        /// </summary>
        internal static string testRemoveHttpProtocolResult {
            get {
                return ResourceManager.GetString("testRemoveHttpProtocolResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;link href=&quot;https://leave&quot; rel=&apos;alternate external&apos;&gt;&lt;link href=&quot;https://leave&quot; rel=external&gt;&lt;link href=&quot;https://leave&quot; rel=&quot;external&quot;&gt;&lt;link href=&quot;http://example.com/style.css&quot;/&gt;&lt;script src  =  &apos;https://www.example.com/script.js&apos;&gt;&lt;/script&gt;&lt;a href= &quot;//google.com&quot;&gt;&lt;/a&gt;&lt;img src   =&quot;/pic.jpg&quot;&gt;&lt;img alt=&quot;http://leave&quot; src  =  &quot;https://img&quot;/&gt;.
        /// </summary>
        internal static string testRemoveHttpsProtocol {
            get {
                return ResourceManager.GetString("testRemoveHttpsProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;link href=&quot;https://leave&quot; rel=&apos;alternate external&apos;&gt;&lt;link href=&quot;https://leave&quot; rel=external&gt;&lt;link href=&quot;https://leave&quot; rel=&quot;external&quot;&gt;&lt;link href=&quot;http://example.com/style.css&quot;/&gt;&lt;script src=&apos;//www.example.com/script.js&apos;&gt;&lt;/script&gt;&lt;a href=&quot;//google.com&quot;&gt;&lt;/a&gt;&lt;img src=&quot;/pic.jpg&quot;&gt;&lt;img alt=&quot;http://leave&quot; src=&quot;//img&quot;/&gt;.
        /// </summary>
        internal static string testRemoveHttpsProtocolResult {
            get {
                return ResourceManager.GetString("testRemoveHttpsProtocolResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input type=&quot;password&quot;&gt; &lt;input type=&quot;text&quot;/&gt; &lt;input type  =  text id=&quot;id&quot;&gt; &lt;input type=&apos;text&apos; id=&apos;id&apos;/&gt;.
        /// </summary>
        internal static string testRemoveInputAttributes {
            get {
                return ResourceManager.GetString("testRemoveInputAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input type=&quot;password&quot;&gt; &lt;input/&gt; &lt;input id=&quot;id&quot;&gt; &lt;input id=&apos;id&apos;/&gt;.
        /// </summary>
        internal static string testRemoveInputAttributesResult {
            get {
                return ResourceManager.GetString("testRemoveInputAttributesResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a   b=&quot;1&quot;&gt;   &lt;b&gt; &lt;c/&gt;   
        ///   &lt;d /&gt;
        ///&lt;pre    a   =   &quot;  1  &quot;&gt;    &lt;x   /&gt;    &lt;y&gt;   &lt;/pre&gt;
        ///
        ///&lt;!--[if lt IE 7 ]&gt;        &lt;body class=&quot;ie6&quot;&gt;      &lt;![endif]--&gt;           &lt;!--[if lt IE 7 ]&gt;        &lt;body class=&quot;ie6&quot;&gt;      &lt;![endif]--&gt;.
        /// </summary>
        internal static string testRemoveIntertagSpaces {
            get {
                return ResourceManager.GetString("testRemoveIntertagSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a q  =  &quot;qqq&quot;  w   =  &apos;ww&quot;w&quot;w&apos; &gt;   
        ///	&lt;b&gt;   
        ///		&lt;c&gt;
        ///			&lt;![CDATA[
        ///			&lt;a&gt;   &lt;b&gt;   &lt;!-- comment --&gt;   &lt;c&gt;
        ///			]]&gt;
        ///		&lt;/c&gt;
        ///	&lt;/b&gt;
        ///&lt;a&gt;
        ///&lt;x /&gt;
        ///&lt;y&gt;    aaa          bbbb          &lt;/y&gt;
        ///.
        /// </summary>
        internal static string testRemoveIntertagSpaces1 {
            get {
                return ResourceManager.GetString("testRemoveIntertagSpaces1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a b=&quot;1&quot;&gt;&lt;b&gt;&lt;c/&gt;&lt;d/&gt;&lt;pre a=&quot; 1 &quot;&gt;    &lt;x   /&gt;    &lt;y&gt;   &lt;/pre&gt;&lt;!--[if lt IE 7 ]&gt;&lt;body class=&quot;ie6&quot;&gt;&lt;![endif]--&gt;&lt;!--[if lt IE 7 ]&gt;&lt;body class=&quot;ie6&quot;&gt;&lt;![endif]--&gt;.
        /// </summary>
        internal static string testRemoveIntertagSpacesResult {
            get {
                return ResourceManager.GetString("testRemoveIntertagSpacesResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a q=&quot;qqq&quot; w=&apos;ww&quot;w&quot;w&apos;&gt;&lt;b&gt;&lt;c&gt;
        ///			&lt;![CDATA[
        ///			&lt;a&gt;   &lt;b&gt;   &lt;!-- comment --&gt;   &lt;c&gt;
        ///			]]&gt;
        ///		&lt;/c&gt;&lt;/b&gt;&lt;a&gt;&lt;x/&gt;&lt;y&gt;    aaa          bbbb          &lt;/y&gt;.
        /// </summary>
        internal static string testRemoveIntertagSpacesResult1 {
            get {
                return ResourceManager.GetString("testRemoveIntertagSpacesResult1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a onclick=&quot;javascript: alert()&quot; onmousemove=&quot;move()&quot; onmouseenter=&quot;javascript:alert();&quot; href=&quot;javascript:alert()&quot;&gt;.
        /// </summary>
        internal static string testRemoveJavaScriptProtocol {
            get {
                return ResourceManager.GetString("testRemoveJavaScriptProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a onclick=&quot;alert()&quot; onmousemove=&quot;move()&quot; onmouseenter=&quot;alert();&quot; href=&quot;javascript:alert()&quot;&gt;.
        /// </summary>
        internal static string testRemoveJavaScriptProtocolResult {
            get {
                return ResourceManager.GetString("testRemoveJavaScriptProtocolResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;link type = &quot;text/css&quot;&gt;&lt;/link&gt;
        ///&lt;link type = &quot;text/plain&quot; rel=&quot;stylesheet&quot;&gt;&lt;/link&gt;
        ///&lt;link type = text/css rel=stylesheet&gt;&lt;/link&gt;
        ///&lt;link type = &apos;text/plain&apos; rel=&apos;alternate stylesheet&apos;&gt;&lt;/link&gt;
        ///&lt;link rel=stylesheet&gt;&lt;/link&gt;.
        /// </summary>
        internal static string testRemoveLinkAttributes {
            get {
                return ResourceManager.GetString("testRemoveLinkAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;link type=&quot;text/css&quot;&gt;&lt;/link&gt; &lt;link rel=&quot;stylesheet&quot;&gt;&lt;/link&gt; &lt;link rel=stylesheet&gt;&lt;/link&gt; &lt;link rel=&apos;alternate stylesheet&apos;&gt;&lt;/link&gt; &lt;link rel=stylesheet&gt;&lt;/link&gt;.
        /// </summary>
        internal static string testRemoveLinkAttributesResult {
            get {
                return ResourceManager.GetString("testRemoveLinkAttributesResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a s=&quot;1 2&quot; style=&quot;a : 1 ;&quot;&gt;&lt;a&gt;&lt;b/&gt;&lt;c/&gt;&lt;d&gt;&lt;pre a=&quot; 1 &quot;&gt;    &lt;x   /&gt;    &lt;y&gt;   &lt;/pre&gt;.
        /// </summary>
        internal static string testRemoveMultiSpaces {
            get {
                return ResourceManager.GetString("testRemoveMultiSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a s=&quot;1 2&quot; style=&quot;a : 1 ;&quot;&gt;&lt;a&gt;&lt;b/&gt;&lt;c/&gt;&lt;d&gt;&lt;pre a=&quot; 1 &quot;&gt;    &lt;x   /&gt;    &lt;y&gt;   &lt;/pre&gt;.
        /// </summary>
        internal static string testRemoveMultiSpacesResult {
            get {
                return ResourceManager.GetString("testRemoveMultiSpacesResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a xxx=&quot;asd 123&quot; ccc = &apos;eee&apos; /&gt;
        ///&lt;a xxx=&quot;123&quot; style=&quot;a:1;b:2&quot; ccc = &apos;eee&apos;/&gt;
        ///&lt;a xxx=&quot;123&quot; ccc = &apos;eee&apos;
        ////&gt;
        ///&lt;a xxx=&quot;123&quot; ccc = &quot;eee&quot; &gt;
        ///&lt;a xxx=&quot;123&quot; ccc = &apos;eaa&quot;e&quot;eaa&apos;&gt;
        ///&lt;a xxx=&quot;123&quot; ccc = &apos;eee&apos;&gt;.
        /// </summary>
        internal static string testRemoveQuotes {
            get {
                return ResourceManager.GetString("testRemoveQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a xxx=&quot;asd 123&quot; ccc=eee /&gt; &lt;a xxx=123 style=&quot;a:1;b:2&quot; ccc=eee /&gt; &lt;a xxx=123 ccc=eee /&gt; &lt;a xxx=123 ccc=eee&gt; &lt;a xxx=123 ccc=&apos;eaa&quot;e&quot;eaa&apos;&gt; &lt;a xxx=123 ccc=eee&gt;.
        /// </summary>
        internal static string testRemoveQuotesResult {
            get {
                return ResourceManager.GetString("testRemoveQuotesResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type = &quot;text/javascript&quot; language=&quot;javascript&quot;&gt;&lt;/script&gt;
        ///&lt;script type=text/javascript language =&apos;javascript&apos; src=&quot;&quot;&gt;&lt;/script&gt;
        ///&lt;script type=&apos;text/javascript&apos; language = javascript&gt;&lt;/script&gt;
        ///&lt;script 
        ///	type = application/javascript
        ///&gt;&lt;/script&gt;.
        /// </summary>
        internal static string testRemoveScriptAttributes {
            get {
                return ResourceManager.GetString("testRemoveScriptAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;&lt;/script&gt; &lt;script src=&quot;&quot;&gt;&lt;/script&gt; &lt;script&gt;&lt;/script&gt; &lt;script&gt;&lt;/script&gt;.
        /// </summary>
        internal static string testRemoveScriptAttributesResult {
            get {
                return ResourceManager.GetString("testRemoveScriptAttributesResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;a&quot;/&gt; qwe   =   eee &lt;a href =&quot;x&quot; /&gt; &lt;a href=  &quot;x&quot;/&gt; &lt;a href  =  &quot;x&quot;  &gt; &lt;input value=&quot;test&quot;  /&gt; &lt;input value=test  /&gt; &lt;input value=test  &gt; &lt;br /&gt;.
        /// </summary>
        internal static string testRemoveSpacesInsideTags {
            get {
                return ResourceManager.GetString("testRemoveSpacesInsideTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;a&quot;/&gt; qwe   =   eee &lt;a href=&quot;x&quot;/&gt; &lt;a href=&quot;x&quot;/&gt; &lt;a href=&quot;x&quot;&gt; &lt;input value=&quot;test&quot;/&gt; &lt;input value=test /&gt; &lt;input value=test&gt; &lt;br/&gt;.
        /// </summary>
        internal static string testRemoveSpacesInsideTagsResult {
            get {
                return ResourceManager.GetString("testRemoveSpacesInsideTagsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style type = &quot;text/style&quot;&gt;&lt;/style&gt;
        ///&lt;style type=text/style &gt;&lt;/style&gt;
        ///&lt;style type=&apos;text/style&apos; &gt;&lt;/style&gt;.
        /// </summary>
        internal static string testRemoveStyleAttributes {
            get {
                return ResourceManager.GetString("testRemoveStyleAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style&gt;&lt;/style&gt; &lt;style&gt;&lt;/style&gt; &lt;style&gt;&lt;/style&gt;.
        /// </summary>
        internal static string testRemoveStyleAttributesResult {
            get {
                return ResourceManager.GetString("testRemoveStyleAttributesResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input checked&gt; &lt;input checked=&quot;checked&quot;&gt; checked=&quot;checked&quot; &lt;input selected = &apos;&apos;&gt; &lt;input disabled=disabled&gt; &lt;input readonly=&apos;true&apos; id=&quot;id&quot;/&gt;.
        /// </summary>
        internal static string testSimpleBooleanAttributes {
            get {
                return ResourceManager.GetString("testSimpleBooleanAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input checked&gt; &lt;input checked&gt; checked=&quot;checked&quot; &lt;input selected&gt; &lt;input disabled&gt; &lt;input readonly id=&quot;id&quot;/&gt;.
        /// </summary>
        internal static string testSimpleBooleanAttributesResult {
            get {
                return ResourceManager.GetString("testSimpleBooleanAttributesResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot;
        ///        &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;.
        /// </summary>
        internal static string testSimpleDoctype {
            get {
                return ResourceManager.GetString("testSimpleDoctype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;.
        /// </summary>
        internal static string testSimpleDoctypeResult {
            get {
                return ResourceManager.GetString("testSimpleDoctypeResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaa &lt;br&gt; &lt;p style=&quot;&quot;&gt; bbbb &lt;br/&gt; ccccccc &lt;/p&gt; &lt;b&gt; ddddd &lt;/b&gt; eeeeeeee.
        /// </summary>
        internal static string testSurroundingSpaces {
            get {
                return ResourceManager.GetString("testSurroundingSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaa&lt;br&gt;&lt;p style=&quot;&quot;&gt;bbbb&lt;br/&gt;ccccccc&lt;/p&gt;&lt;b&gt; ddddd &lt;/b&gt; eeeeeeee.
        /// </summary>
        internal static string testSurroundingSpacesResult {
            get {
                return ResourceManager.GetString("testSurroundingSpacesResult", resourceCulture);
            }
        }
    }
}